name: flutter_awesome_circular_chart
description: Animated radial and pie charts for Flutter
version: 1.1.0
homepage: https://github.com/xjodoin/flutter_awesome_circular_chart

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.4.1 <4.0.0"
